export const homeObjOne = {
id: 'about',
lightBg: false,
lightText: true,
lightTextDesc: true,
topLine: 'Card One',
headline: 'Random text about the Card One.',
description: 'Get this card ........................................ some description',
buttonLabel: 'Get Started',
imgStart: false,
img: require('../../images/car.svg').default,
alt: 'Car',
dark: true,
primary: true,
darkText: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Card One',
    headline: 'Random text about the Card One.',
    description: 'Get this card ........................................ some description',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/car.svg').default,
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true,
    };

    export const homeObjThree = {
        id: 'signup',
        lightBg: false,
        lightText: true,
        lightTextDesc: true,
        topLine: 'Card One',
        headline: 'Random text about the Card One.',
        description: 'Get this card ........................................ some description',
        buttonLabel: 'Get Started',
        imgStart: true,
        img: require('../../images/car.svg').default,
        alt: 'Car',
        dark: true,
        primary: true,
        darkText: false,
        };